# Generated by Django 4.0.1 on 2022-01-23 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Published', models.DateTimeField(default=django.utils.timezone.now)),
                ('Vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('VOte_ratio', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
