# Generated by Django 4.0.1 on 2022-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tags_rename_name_project_title_project_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Tags',
        ),
        migrations.AddField(
            model_name='project',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
