# Generated by Django 4.0.1 on 2022-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_title_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='photosdefault.jpg', null=True, upload_to='photos/'),
        ),
    ]
